delimiter $$

CREATE DATABASE `iris` /*!40100 DEFAULT CHARACTER SET latin1 */$$

CREATE TABLE `DATA_SET` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `SEPAL_LENGTH` double DEFAULT NULL,
  `SEPAL_WIDTH` double DEFAULT NULL,
  `PETAL_LENGTH` double DEFAULT NULL,
  `PETAL_WIDTH` double DEFAULT NULL,
  `SPECIES` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=151 DEFAULT CHARSET=latin1$$